
project_id = "mgjodiqecnnltsgorife"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
schema = "public"
shadow_schema = "shadow"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325
uri = "http://localhost:54321/auth"

[migrations]
enabled = false

[functions]
enabled = true

[functions.upload-file-to-openai]
verify_jwt = true

[functions.create-openai-assistant]
verify_jwt = true
