
project_id = "mgjodiqecnnltsgorife"

[functions]
[functions.chat]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-table-exists]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.check-drive-access]
verify_jwt = false

[functions.check-url-access]
verify_jwt = false

[functions.get_agent_dashboard_stats]
verify_jwt = false

[functions.execute_sql]
verify_jwt = false

[functions.get_client_agent_data]
verify_jwt = false

[functions.get_client_agent_names]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.send-deletion-email]
verify_jwt = false

