
project_id = "mgjodiqecnnltsgorife"

[functions]
[functions.chat]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-client-invitation]
verify_jwt = false

[functions.send-deletion-email]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.send-recovery-confirmation]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = false

[functions.verify-recovery-token]
verify_jwt = false

[functions.check-table-exists]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.generate-client-password]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.check-drive-access]
verify_jwt = true

[functions.check-url-access]
verify_jwt = true
