
# Project configuration
project_id = "mgjodiqecnnltsgorife"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Auth configuration
[auth]
enabled = true
site_url = "https://preview--welcomechat.lovable.app"
additional_redirect_urls = [
  "https://localhost:3000",
  "https://preview--welcomechat.lovable.app",
  "https://welcomechat.lovable.app"
]

# Real-time configuration
[realtime]
enabled = true

# Storage configuration
[storage]
enabled = true

# Edge Functions configuration
[functions]
enabled = true

# Inbucket configuration
[inbucket]
enabled = true
port = 54328

# Analytics configuration
[analytics]
enabled = false
port = 54327
