
project_id = "mgjodiqecnnltsgorife"

[script]
command = [
  "deno",
  "run",
  "--allow-net",
  "--allow-env",
  "--allow-read",
  "index.ts"
]

# Add the LlamaCloud API key to the Edge Function secrets
# The actual key is managed via Supabase secrets, not stored here
# Run this command to add the key:
# supabase secrets set LLAMA_CLOUD_API_KEY="llx-nWkZDxIAla894faWWoAWe8uX7WNhRrEdWOkHdzRiigyck4eT"
